import "@mantine/core/styles.css";
import { Container, Image, Text, Center } from "@mantine/core";

import { TitleImage } from "./TitleImage";

export default function Main() {
  
  return <div>
    <TitleImage/>

    <Container size="md">
 <br></br>
<p><span >Five years ago, fifteen-year-old </span><a href="https://time.com/person-of-the-year-2019-greta-thunberg/"><span >Greta Thunberg</span></a><span > rose to fame as an international hero for climate change. Her &ldquo;school strike&rdquo; gained substantial media attention, influencing millions of young people around the world to join her in protesting through </span><a href="https://fridaysforfuture.org/what-we-do/who-we-are/"><span >Global Climate Strikes</span></a><span >. In 2019, her powerful </span><a href="https://www.npr.org/2019/09/23/763452863/transcript-greta-thunbergs-speech-at-the-u-n-climate-action-summit"><span >&ldquo;How dare you&rdquo;</span></a><span > speech at the U.N. Climate Action Summit inspired people across generations. Greta&rsquo;s rise to fame coincided with a global awakening to the severe urgency of the climate crisis. Now, in 2025, the fire lit by Greta has fizzled to the periphery of American politics. The once priority ranked concerningly low among issues in the 2024 election, even among Democrats, according to Gallup polls.&nbsp;</span></p>
 
<p><span >In President Donald Trump&rsquo;s first one hundred days in office, his environmental policy made the news, but captured relatively little public attention. The U.S. pulled out of the Paris Agreement again, just as it did in Trump&rsquo;s first term. Trump imposed an </span><a href="https://www.whitehouse.gov/presidential-actions/2025/04/protecting-american-energy-from-state-overreach/?utm_source=wh_social_share_button"><span >executive order</span></a><span > attempting to prevent states from enacting energy policies which restrict or fine companies for greenhouse gas emissions. The administration has also proposed hundreds of millions of dollars in </span><a href="https://www.science.org/content/article/trump-seeks-end-climate-research-premier-u-s-climate-agency"><span >funding cuts for climate research</span></a><span >, and opened public land to </span><a href="https://www.nytimes.com/2025/04/08/climate/trump-new-mexico-nevada-mining-drilling.html"><span >mining, drilling, and logging</span></a><span >. Trump&rsquo;s approach to environmental policy can be described as industry-friendly at best and hostile at worst. Despite these alarming headlines, these stories all exist in the shadow of tariffs, immigration, and the brewing constitutional crisis. Democrats are understandably prioritizing the seemingly more immediate concerns, but at what expense?&nbsp;</span></p>
 
<p><span >The relatively low media coverage of climate change both influences and is influenced by American priorities. Throughout American history, especially the last three decades, media coverage of climate change has played a large role in shaping public opinion. While scientific consensus on climate charge has only strengthened over time, the degree to which the public cares about the climate has fluctuated with the news cycle. The following timeline examines how public attitudes towards the climate crisis have shifted over time, with the goal of illuminating broader patterns in American culture.&nbsp;</span></p>
 <br></br>
<p><strong>Climate Change in Politics and Media: A History</strong></p>
 
<p><em><span >Late 1990s: Initial Political Framework</span></em></p>
 
<p><span >The politicalization of climate change in the U.S.</span> <span >arguably began with the </span><a href="https://treaties.un.org/Pages/ViewDetails.aspx?src=IND&amp;mtdsg_no=XXVII-7-a&amp;chapter=27&amp;clang=_en"><span >Kyoto Protocol</span></a><span >. In 1997, representatives from around the world met in Japan and established a binding agreement for developed countries to reduce greenhouse gas emissions. At the time, environmental conservation and protection was a bipartisan issue &mdash;there was relative consensus that humanity&rsquo;s habitat deserved protection. The Kyoto Protocol, however, stirred controversy in that it excluded developing countries &mdash; an exemption seemingly antithetical to the view of climate change as a global issue. Furthermore, reducing greenhouse gases would come at the expense of industry. As a result, Kyoto was portrayed in the U.S. media as a debate of &ldquo;environment vs. economy.&rdquo; Although the U.S. initially signed on to the agreement, the Senate opted against ratifying it for economic reasons. While Kyoto marks the first major moment of political strain over the climate, there was little urgency to spotlight the issue in the media. Consequently, public awareness and likewise public concern about the climate was low at the turn of the century.&nbsp;</span></p>
 
<p><span >Despite low public awareness, various affected industries recognized the threat posed by the Kyoto Protocol and influenced the emergence of climate change denial groups. Fossil fuel and heavy manufacturing companies joined and funded denial groups like the </span><a href="https://climateinvestigations.org/global-climate-coalition-documents/"><span >Global Climate Coalition (GCC)</span></a><span >. The GCC spread misinformation about climate change throughout the 90s and ensured loud messaging to combat Kyoto. Their rhetoric reached a broad audience, effectively rendering climate science &ldquo;debatable&rdquo; in public discourse, further intensifying its political dimension.&nbsp;</span></p>
 
<Center><Image w="600px" src="./assets/kyoto.png"></Image></Center>

<Text ta="center" size="12px"><span>GCC Advertisement ran in a 1997 </span><em><span >New York Times </span></em><span >paper, source: </span><a href="https://climateinvestigations.org/global-climate-coalition-koch-exxon/"><span >Climate Investigation Center</span></a></Text>
 
<p><em><span >Mid-2000s: Increasing Awareness</span></em></p>
 
<p><span >The mid-2000s marked an increase in climate change portrayal in cinema and in the news media. The 2004 disaster film,&ldquo;</span><a href="https://yaleclimateconnections.org/2024/05/the-enduring-influence-of-the-day-after-tomorrow-20-years-later/"><span >The Day After Tomorrow&rdquo;</span></a><span > depicted catastrophic climate scenarios, which many deemed as exaggerated fear mongering. The film gained popularity quickly and marked an upward shift in public knowledge of climate change. Alongside increased public awareness, however, came increased misinformation. Critics questioned the film&rsquo;s accuracy, fueling denial groups. Two years later, in 2006, Al Gore&rsquo;s </span><a href="https://www.imdb.com/title/tt0497116/"><span >&ldquo;An Inconvenient Truth&rdquo;</span></a><span > documentary was released and received extensive media coverage. Gore&rsquo;s identity as a mainstream politician and former presidential candidate helped legitimize climate change as a cause, but skeptics remained vocal. The overall result was a spike in awareness of climate change among Americans, although little tangible action was taken.&nbsp;</span></p>
 
<p><span >In 2007, the Intergovernmental Panel on Climate Change (IPCC) released their </span><a href="https://www.ipcc.ch/report/ar4/syr/"><span >Fourth Assessment Report</span></a><span > on climate change which cited human activity as a &ldquo;very likely&rdquo; cause of global warming. The report gained substantial media attention for its strong and decisive conclusion. The Bush administration, previously hesitant to acknowledge climate change as a legitimate concern, recognized the validity of these findings. In the same year, Gore and the IPCC received the Nobel Peace Prize for their activism. These events positioned climate policy at the center of national discourse approaching a presidential election year.&nbsp;</span></p>
 
<p><em><span >Obama Era: Climate as Major Political Issue</span></em></p>
 
<p><span >In the 2008 election, energy and environmental issues ranked among the top three concerns for voters for the first time, according to Gallup polls. Both candidates, John McCain and Barack Obama, outlined their plans for biofuels, renewables, nuclear power, and oil drilling. Though their positions varied, the mere discussion of environmental issues in a presidential election represented a major shift. The </span><a href="https://archive.nytimes.com/www.nytimes.com/elections/2008/president/issues/climate.html?src=tp"><span >New York Times election guide</span></a><span > detailed the candidates&rsquo; positions on these issues, signalling the salience of climate issues to voters. Presidential debates covered climate change both explicitly and implicitly, with environmental concerns frequently arising during economic discussions. Public opinion aligned with this political focus, with 77% of Americans citing climate change as &ldquo;very important&rdquo; to their vote, according to Pew Research.</span></p>
 
<p><span >Although Obama was the favorite candidate for voters concerned about the environment, he largely failed to deliver on campaign promises during his tenure. In 2009, world leaders met at the </span><a href="https://www.c2es.org/content/cop-15-copenhagen/"><span >Copenhagen Climate Conference</span></a><span > to negotiate a plan for reducing global carbon emissions. Unfortunately, the minimal progress made in Copenhagen left many unsatisfied &mdash; the countries failed to reach a binding agreement or even establish a timeline for creating one. This trend of disappointment continued when the </span><a href="https://www.c2es.org/content/cap-and-trade-basics/"><span >&ldquo;cap and trade&rdquo;</span></a><span > legislation failed in the Senate. &ldquo;Cap and trade,&rdquo; outlined on the campaign trail, involved setting a cap on carbon emissions and distributing emission allowances to companies who could then trade the allowances amongst themselves. Opponents feared for economic effects of capping emissions, and successfully reframed the bill as &ldquo;cap and tax,&rdquo; a particularly damaging characterization during a period of financial instability. The negative rhetoric stuck, to the extent that proponents determined that moving forward with the &ldquo;cap and trade&rdquo; was just politically infeasible. Instead of trying to rebrand the policy, which had been successful in other countries, the Obama administration and its allies just discarded it entirely. This squelched much of the administration&rsquo;s momentum towards climate policy &mdash; the public, who had once appeared to issue an electoral mandate to act on the climate, now seemed disinterested.</span></p>
 
<p><span >During Obama&rsquo;s presidency, natural disasters periodically reignited public attention to climate change. </span><a href="https://weather.metoffice.gov.uk/learn-about/weather/case-studies/hurricane-sandy"><span >Hurricane Sandy</span></a><span > hit the East Coast in 2012 resulting in a temporary surge of climate-related news coverage. While debate continued about whether these tragedies were evidence of human activity&rsquo;s effect on the environment, fewer individuals are willing to oppose climate change when tragedy occurs. Furthermore, the tragic and very tangible effects left behind by hurricanes motivated calls for change. While each natural disaster generates calls for action in the short-term, they clearly do not move the public, or elected officials, enough to create substantive change. FEMA&rsquo;s disaster prevention efforts are minimally funded, fractional in comparison the funds allocated to reactive disaster relief. Even in the wake of natural disasters, calls to increase the percentage of FEMA&rsquo;s budget allocated toward prevention efforts are few and far between.</span></p>
 
<Center> <Image w="600px" src="./assets/bloomberg.webp"></Image></Center>
<Text ta="center" size="12px"><span >Cover of Bloomberg Magazine after Hurricane Sandy, source: </span><a href="https://www.npr.org/sections/thetwo-way/2012/11/01/164106889/bloomberg-businessweeks-cover-its-global-warming-stupid"><span >NPR</span></a></Text>

<p><em><span >2016 Election: Rising Attention and Polarization</span></em></p>
 
<p><span >In 2015, the </span><a href="https://unfccc.int/process-and-meetings/the-paris-agreement"><span >Paris Climate Agreement</span></a><span > represented a substantial achievement in climate policy history and generated significant media attention. Historically, international cooperation for reducing emissions proved challenging because any effective plan requires unanimous commitment. So, when all the major players finally agreed, it was a huge step. That being said, in the U.S. this &ldquo;solution&rdquo; created a false sense of climate stability. Many overlooked the need for ongoing adherence to the agreement and the persistent tensions among participating nations. Conservation efforts require continuous commitment rather than one-time solutions. The Paris Agreement did not &ldquo;solve&rdquo; climate change, but it provided enough perceived stability for climate issues to be overlooked in the 2016 election.</span></p>
 
<p><span >From a media coverage perspective, climate change rarely arose during the 2016 election. On the surface, this stark contrast appears to represent regression from 2008. The slow progress since 2008 created an illusion that sufficient legislative solutions were in place, which contributed to climate change ranking low among voter priorities. America&rsquo;s political landscape underwent a dramatic shift in 2016 with Donald Trump&rsquo;s election, reflecting widespread desire for significant governmental change and dissatisfaction with the status quo. This sentiment proved to supersede climate change as an issue. The apathy of voters towards climate change in the 2016 election is reinforced by Trump&rsquo;s election in itself &mdash; voters elected a candidate who has staunchly maintained that climate change is a hoax. In 2017, his quick move to withdraw from the Paris Agreement aligned with the sweeping changes his supporters had hoped for. While the decision received media coverage, it was largely overshadowed by other controversial administration policies. This era marked a profound shift in American perceptions of environmental issues: what was once viewed as a universal threat had transformed into an entirely political and </span><em><span >debatable</span></em><span > issue. At this point, climate change was one of many issues being increasingly polarized under Trump.&nbsp;</span></p>
 
<p><em><span >Late-2010s: Peak Activism and Subsequent Decline</span></em></p>
 
<p><span >In 2018, the IPCC&rsquo;s Special Report on global warming catalyzed renewed fear and heightened conversation around climate change. The special report predicted the future of the planet if temperatures continue to rise; it contrasted what would happen if temperatures increase by only 1.5&deg;C above pre-industrial levels, compared to if they increase by 2&deg;C or more. An increase of 1.5&deg;C would result in significantly less damage than a 2&deg;C increase. The report emphasized that neither scenario was favorable, but that a 1.5&deg;C increase was virtually inevitable. While inherently negative, the report highlighted a silver lining: with drastic changes, humanity could prevent warming of 2&deg;C and preserve some aspects of our environment. This gave rise to the &ldquo;12 years to act&rdquo; narrative, which quickly surged to contemporary relevance. This narrative framed climate change as an existential issue &mdash; a framing that resonated deeply with young Americans, many of whom have come to see climate change as a generation-defining issue. The urgency of this message mobilized Americans, transforming mere awareness into real action.&nbsp;</span></p>
 
<p><span >In the year that followed, climate coverage arguably grew to the highest levels since 2008. From 2015 to 2019, the planet experienced record breaking global temperatures and greenhouse gas emissions. This, paired with the alarming &ldquo;12 years to act,&rdquo; massively shaped public opinion. In September, 2019, Swedish youth activist Greta Thunberg started a trend of global &ldquo;school-strikes&rdquo; to protest for the climate. The unprecedented number of strikers made waves in the news and sparked conversation and action across generations. At the same time, talks of a Green New Deal gained popularity among progressives, however, like the &ldquo;cap and trade&rdquo; saga of 2009, the catchy name became polarizing and legislation never passed.</span></p>

<Center><Image w="500px" src="./assets/greta.webp"></Image></Center>
<Text ta="center" size="12px"><span >Greta Thunberg, TIME Person of the Year, source: </span><a href="https://time.com/person-of-the-year-2019-greta-thunberg/"><span >TIME magazine</span></a></Text>

<p><span >In 2020, the COVID-19 pandemic justifiably stole attention from all other issues. The election year boded well for climate enthusiasts, however most attribute Trump&rsquo;s ousting to the pandemic and the struggling economy. Biden&rsquo;s campaign avoided the already-branded Green New Deal, though promised many of the same climate-oriented policies. Upon taking office, President Biden rejoined the Paris Agreement and made efforts to lower greenhouse gases. The news was celebrated, although it received criticisms from progressives for being too moderate. In 2022, Biden signed the </span><a href="https://www.edf.org/biggest-thing-congress-has-ever-done-address-climate-change?ub_tg=372&amp;ub_o=26&amp;ub_cta=4&amp;ub_f=m&amp;utm_source=google&amp;utm_campaign=edf_none_upd_pmt&amp;utm_medium=ad&amp;utm_id=1733940309&amp;gad_source=1&amp;gad_campaignid=19544681221&amp;gbraid=0AAAAAD9QDCxas6EzK__CmI3bU6iMHdldj&amp;gclid=Cj0KCQjww-HABhCGARIsALLO6XxE2AwJRFQIqPtsgVVkbkFqU6_2o-Loa3p1ji9gDzPLn1IHLMhky2EaAjYVEALw_wcB&amp;gclsrc=aw.ds"><span >Inflation Reduction Act</span></a><span >, which invested over $300 billion in climate and clean energy, making history as the largest climate legislation passed by Congress. (conclusion sentence)&nbsp;</span></p>
 
<p><em><span >Present: Trump&rsquo;s Second Term</span></em></p>

<p><span >The 2024 election saw reduced climate coverage due to continued public dissatisfaction with the federal government and rising inflation. Once again, Americans prioritized immediate concerns over the future of the environment, a fact unsurprising given historical patterns. Unfortunately, Trump&rsquo;s second term has been detrimental for the environment &mdash; funding cuts for climate research, withdrawal from the Paris Climate Agreement, and of course, his famous </span><a href="https://www.weforum.org/stories/2025/03/us-enters-drill-era-top-energy-leader-oil-gas/"><span >&ldquo;Drill Baby Drill&rdquo;</span></a><span > refrain in reference to his support of fracking. News coverage, however, has been focused elsewhere, to what it regards as more urgent and more immediate, reflecting climate change&rsquo;s status as a stagnant concern in the U.S. Even on a global scale, other nations seem more worried about tariffs than they do about the U.S. leaving the Paris agreement.&nbsp;</span></p>
<p><br /></p>
<p><strong>Trend Analysis and Takeaways</strong></p>
 
<p><span >Evaluating media coverage of climate change and corresponding public opinion over the past twenty years revealed two main trends which help explain why climate coverage feels absent in the media in 2025.&nbsp;</span></p>
 
<p><span >The first obvious pattern evidenced by this timeline is the cyclical nature of media coverage, peaking with alarming IPCC reports or extreme weather events, then quickly falling as other crises emerge. Scientific consensus has often been climate activism&rsquo;s greatest asset, with hard facts igniting collective concern in 2007, and again in 2018, thanks to IPCC reports. Unfortunately, powerful distractions, such as the 2008 recession and the 2020 pandemic, repeatedly push climate change to the periphery of public consciousness. Climate change is particularly vulnerable to this attention cycle because of its gradual &mdash; and almost invisible &mdash; daily impact on most Americans&rsquo; lives. Unlike a stock market crash or a pandemic, climate change does not bring daily life to a halt &mdash; it creeps in through slightly worse hurricane seasons, gradual animal extinctions, and volatile seasonal changes. This subtle encroachment, combined with our 24-hour news cycle that prioritizes novelty over persistence, creates a perfect storm for climate neglect. When today&rsquo;s science says we&rsquo;re approaching irreversible tipping points rather than offering hopeful solutions, both journalists and audiences seem to look away, preferring more solvable problems with clearer pathways to resolution.</span></p>
 
<p><span >Furthermore, the polarization of climate change, which has grown over time, has impeded the development of workable climate policy. The fossil fuel industry successfully reframed climate science into a political debate, evidenced by the repeated dismantling of promising climate initiatives and culminating in Trump&rsquo;s reelection in 2024. Media coverage bears substantial responsibility for this polarization &mdash; policies with catchy names like &ldquo;cap and trade&rdquo; and the Green New Deal were so effectively vilified as economic threats that Democrats had to abandon them entirely. This has created a destructive cycle where ambitious proposals needed to address the climate crisis are immediately vulnerable to negative press. The result is our current media landscape, where climate coverage has virtually disappeared from headlines despite worsening conditions.&nbsp;</span></p>
 
<p><span >For better or for worse, this silence won&rsquo;t persist indefinitely. History has evidenced that climate coverage, and consequent public attention, is cyclical. Inevitably, the climate will again be a news fixture, whether it be because of natural disasters and devastation, bleak IPCC reports, or attempts at diplomatic and political policy solutions. The question, really, is what will break the cycle. Which hurricane, scientific report, or politician will finally get Americans to view climate change as an urgent, wildly disruptive existential problem worth the attention of a pandemic or stock market crash? Will it be too late?&nbsp;</span></p>
<p><br /><br /><br /><br /><br /><br /></p>
<p><span >References&nbsp;</span></p>
<p><a href="https://news.gallup.com/poll/651719/economy-important-issue-2024-presidential-vote.aspx"><span >https://news.gallup.com/poll/651719/economy-important-issue-2024-presidential-vote.aspx</span></a><span >&nbsp;</span></p>
 
<p><a href="https://www.earthday.org/climate-change-in-the-media-public-perception-and-the-responsibility-of-news-outlets/"><span >https://www.earthday.org/climate-change-in-the-media-public-perception-and-the-responsibility-of-news-outlets/</span></a><span >&nbsp;</span></p>
 
<p><a href="https://www.climateforesight.eu/articles/success-or-failure-the-kyoto-protocols-troubled-legacy/"><span >https://www.climateforesight.eu/articles/success-or-failure-the-kyoto-protocols-troubled-legacy/</span></a><span >&nbsp;</span></p>
 
<p><a href="https://yaleclimateconnections.org/2024/05/the-enduring-influence-of-the-day-after-tomorrow-20-years-later/"><span >https://yaleclimateconnections.org/2024/05/the-enduring-influence-of-the-day-after-tomorrow-20-years-later/</span></a></p>
 
<p><a href="https://www.pewresearch.org/politics/2006/07/12/little-consensus-on-global-warming/"><span >https://www.pewresearch.org/politics/2006/07/12/little-consensus-on-global-warming/</span></a></p>
 
<p><a href="https://www.nytimes.com/2007/02/03/science/earth/03climate.html?ex=1328158800&amp;en=61f42312221df544&amp;ei=5090&amp;partner=rssuserland&amp;emc=rss%3Cbr%20/%3E"><span >https://www.nytimes.com/2007/02/03/science/earth/03climate.html?ex=1328158800&amp;en=61f423</span></a></p>
<p><a href="https://www.nytimes.com/2007/02/03/science/earth/03climate.html?ex=1328158800&amp;en=61f42312221df544&amp;ei=5090&amp;partner=rssuserland&amp;emc=rss%3Cbr%20/%3E"><span >12221df544&amp;ei=5090&amp;partner=rssuserland&amp;emc=rss%3Cbr%20/%3E</span></a><span >&nbsp;</span></p>
 
<p><a href="https://www.tandfonline.com/doi/full/10.1080/09644010902823782"><span >https://www.tandfonline.com/doi/full/10.1080/09644010902823782</span></a><span >&nbsp;</span></p>
 
<p><a href="https://grist.org/article/climates-brief-turn-in-the-spotlight/"><span >https://grist.org/article/climates-brief-turn-in-the-spotlight/</span></a><span >&nbsp;</span></p>
 
<p><a href="https://www.pewresearch.org/politics/2008/08/21/section-3-issues-and-the-2008-election/"><span >https://www.pewresearch.org/politics/2008/08/21/section-3-issues-and-the-2008-election/</span></a><span >&nbsp;</span></p>
 
<p><a href="https://www.nytimes.com/2009/12/19/science/earth/19climate.html"><span >https://www.nytimes.com/2009/12/19/science/earth/19climate.html</span></a><span >&nbsp;</span></p>
 
<p><a href="https://www.nytimes.com/2010/03/26/science/earth/26climate.html"><span >https://www.nytimes.com/2010/03/26/science/earth/26climate.html</span></a><span >&nbsp;</span></p>
 
<p><a href="https://www.npr.org/sections/thetwo-way/2012/11/01/164106889/bloomberg-businessweeks-cover-its-global-warming-stupid"><span >https://www.npr.org/sections/thetwo-way/2012/11/01/164106889/bloomberg-businessweeks-cover-its-global-warming-stupid</span></a><span >&nbsp;</span></p>
 
<p><a href="https://www.brookings.edu/articles/inviting-danger-how-federal-disaster-insurance-and-infrastructure-policies-are-magnifying-the-harm-of-climate-change/"><span >https://www.brookings.edu/articles/inviting-danger-how-federal-disaster-insurance-and-infrastructure-policies-are-magnifying-the-harm-of-climate-change/</span></a></p>
 
<p><a href="https://wmo.int/news/media-centre/global-climate-2015-2019-climate-change-accelerates"><span >https://wmo.int/news/media-centre/global-climate-2015-2019-climate-change-accelerates</span></a><span >&nbsp;</span></p>
<p><a href="https://www.markey.senate.gov/imo/media/doc/five_years_in_a_green_new_deal_world_-_020624pdf.pdf"><span >https://www.markey.senate.gov/imo/media/doc/five_years_in_a_green_new_deal_world_-_020624pdf.pdf</span></a> </p>
    </Container>;
  </div>;
}
