export const longText = `

Five years ago, fifteen-year-old [Greta Thunberg](https://time.com/person-of-the-year-2019-greta-thunberg/) rose to fame as an international hero for climate change. Her "school strike" gained substantial media attention, influencing millions of young people around the world to join her in protesting through [Global Climate Strikes](https://fridaysforfuture.org/what-we-do/who-we-are/). In 2019, her powerful ["How dare you"](https://www.npr.org/2019/09/23/763452863/transcript-greta-thunbergs-speech-at-the-u-n-climate-action-summit) speech at the U.N. Climate Action Summit inspired people across generations. Now, in 2025, the fire lit by Greta has fizzled to the periphery of American politics. The once priority ranked low among issues in the 2024 election, even among Democrats, according to Gallup polls.

In President Donald Trump's first one hundred days in office, his environment-impacting actions made the news, but captured relatively little public attention. The U.S. pulled out of the Paris Agreement again, just as it did in Trump's first term. An [executive order](https://www.whitehouse.gov/presidential-actions/2025/04/protecting-american-energy-from-state-overreach/?utm_source=wh_social_share_button) attempts to restrict states from enacting energy policies which restrict or fine companies for greenhouse gas emissions. The administration has also proposed hundreds of millions in [funding cuts for climate research](https://www.science.org/content/article/trump-seeks-end-climate-research-premier-u-s-climate-agency). Not to mention, Trump helps private industries by opening public land to [mining, drilling, and logging](https://www.nytimes.com/2025/04/08/climate/trump-new-mexico-nevada-mining-drilling.html). Despite these alarming headlines, these stories all live in the shadow of tariffs, immigration, and the brewing constitutional crisis. Democrats are understandably prioritizing the seemingly more immediate concerns, but at what expense?

The relatively low media coverage of climate change both influences and is influenced by American priorities. Throughout American history, especially the last three decades, media coverage of this scientific phenomenon played a large role in public opinion. It is especially impactful given the gradual nature of climate and the difficulty for most people to feel its effects on their daily lives. Interestingly, science has only doubled down on the urgency of the issue, yet the media portrayal, and likewise public opinion, fluctuates like any other issue. With this motivation, the following historical timeline of the politics of climate change examines the public attention shifts of the issue with a goal of illuminating patterns which speak to American priorities and culture.

**Climate Change in Politics and Media: A History**

*Late 1990s: Initial Political Framework*

The politicalization of climate change in the U.S.  arguably began with the [Kyoto Protocol](https://treaties.un.org/Pages/ViewDetails.aspx?src=IND&mtdsg_no=XXVII-7-a&chapter=27&clang=_en). In 1997, representatives from around the world met in Japan and established a binding agreement for developed countries to reduce greenhouse gas emissions. At the time, Americans' valued nature and the environment across the aisle and there was consensus that humanity's habitat deserved protection. However, with climate change being a global issue, Kyoto's exemption of developing countries stirred controversy. Furthermore, reducing greenhouse gases would come at the expense of business. As a result, Kyoto was portrayed in the U.S. media as a debate of "environment vs. economy." Although the U.S. initially signed on to the agreement, the Senate opted against ratifying it for economic reasons. While Kyoto marks the first major moment of political strain over the climate, there was little urgency to spotlight the issue in the media. Consequently, public awareness and likewise public concern about the climate was low at the turn of the century.

Despite low public awareness, various affected industries recognized the threat posed by the Kyoto Protocol and influenced the emergence of climate change denial groups. Fossil fuel and heavy manufacturing companies joined and funded groups like the [Global Climate Coalition (GCC)](https://climateinvestigations.org/global-climate-coalition-documents/). The GCC had an early start in 1989 when climate change science posed a potential future threat; they spread misinformation about climate change throughout the 90s and ensured loud messaging to combat Kyoto. This effectively rendered climate science "debatable" in public discourse, which further intensified its political dimension.

![](./assets/kyoto.png)

GCC Advertisement ran in a 1997 New York Times paper, source: [climateinvestigations.org](https://climateinvestigations.org/global-climate-coalition-koch-exxon/)

*Mid-2000s: Rising Awareness*

The mid-2000s marked an increase in climate change portrayal in cinema and in the news media. The 2004 disaster film,"[The Day After Tomorrow"](https://yaleclimateconnections.org/2024/05/the-enduring-influence-of-the-day-after-tomorrow-20-years-later/) depicted catastrophic climate scenarios, which many deemed as exaggerated fear mongering. The film gained popularity quickly and marked an upward shift in the popularity of climate change. Alongside increased public awareness, however, came increased misinformation. Critics questioned the film's accuracy, fueling denial groups. Two years later, in 2006, Al Gore's ["An Inconvenient Truth"](https://www.imdb.com/title/tt0497116/) documentary was released and received extensive media coverage. Gore's identity as a mainstream politician and former presidential candidate helped legitimize the narrative, but skeptics remained vocal. The overall result was a spike in awareness of climate change among Americans, although little tangible action was taken.`;